### ISSUE TITLE
CJ4 WT Mod does not capture the ILS

### ISSUE THREAD

**Issue by Steel61** [Working-Title-MSFS-Mods/fspackages#1439] opened 2021-11-22 21:29 UTC
After SU7 and installing WT 12.9, I flew three ILS approaches (two at KBGM and one at KPIT) with no luck in capturing the ILS Approach.  I noticed in all three cases there was a Check LOC Tuning message on the CDU, yet the correct ILS frequency was tuned in.  There was no blue dotted CDI to indicate the system had tuned in the LOC and of course going to APPROACH mode on the autopilot did not auto-switch from GPS to ILS.  I manually switched to the ILS mode from the GPS and the green ILS CDI needle was not det on the approach course even though it displayed the correct ident for the ILS on the PFD.  I hope you gents can get us back to where we were before the ASOBO SU7.

**Comment by mattnischan** [comment] 2021-11-22 21:52
Duplicate of #1428

**Closed by mattnischan** 2021-11-22 21:52 UTC
