### ISSUE TITLE
Map distance inconsistency

### ISSUE THREAD

**Issue by odourboy** [Working-Title-MSFS-Mods/fspackages#731] opened 2020-12-30 02:32 UTC
I don't know if this is how tit's 'supposed to work', but in map display, a waypoint distance is inconsistent with distance 'arc'. In screen shot, notice the waypoint DEAKK is 15NM distant and is right on the arc, but the arc indicates 20NM range. This happens for any magnification setting... items of interest are 3/4 of the distance indicated in the arc when they come into view. 

![FlightSimulator 2020-12-28 21-32-38-53](https://user-images.githubusercontent.com/43181324/103326106-d94a5880-4a1c-11eb-95b9-41d789da87ff.jpg)

**Comment by slip664** [comment] 2020-12-30 07:42
Known but complex issue.

**Comment by odourboy** [comment] 2020-12-30 14:36
I figured as much... too obvious to go unnoticed.

**Comment by dga711** [comment] 2021-01-03 13:26
Duplicate of #561 
Will followup there. Thank you

**Closed by dga711** 2021-01-03 13:26 UTC
Labels: CJ4
