### ISSUE TITLE
[CJ4 0.7.0] MCDU FlightPlan import problem

### ISSUE THREAD

**Issue by Nadelbaum** [Working-Title-MSFS-Mods/fspackages#522] opened 2020-11-06 10:56 UTC
Created in SimBrief
Airac 2012
Flight: UUDD-LFSB
Route: DCT SODRU B107 ASKIL/K0656F430 M863 RUDKA T174 TOXAR/K0519F280 T174 WAR/K0633F430 T174 LATAG P861 ASTEL/N0335F430 P861 GOLOP/N0260F240 P861 EROKA L984 OKG/N0334F430 UN869 KEGOS/N0322F410 DCT LUMEL DCT

Errors out during flight plan import through FMS.

**Comment by dga711** [comment] 2020-11-06 14:24
So
1. The NOT IN DATABASE stems from, that SimBrief only posts Runway 32, but there is 32L and 32R, so the game data doesnt know which one.

2. The failing airway is more obscure. My current observation is that game/navigraph data looks like this
![image](https://user-images.githubusercontent.com/2995606/98376561-f9c0ec80-2043-11eb-9ef6-cf303e06c85e.png)
But according to SkyVector it should be 
![image](https://user-images.githubusercontent.com/2995606/98376620-0fcead00-2044-11eb-8a2b-e6a97d13fbc9.png)
So the order of DONAD and BALTU is wrong.

I still need to figure out if it is a mistake on how we load data or it is wrong in Navigraph MSFS data.

**Comment by dga711** [comment] 2020-11-06 14:29
The Navigraph MSFS data seems to give us OKL instead of OKG 🤔 
![image](https://user-images.githubusercontent.com/2995606/98377209-d0549080-2044-11eb-9a4f-1da87ee7513d.png)

**Comment by dga711** [comment] 2020-11-06 16:09
So, right now the problem is that msfs doesn't give us full runway and OKG is missing.
Will need to see how we can fix that.

**Comment by havu1977** [comment] 2020-11-06 16:14
There are 3 runways at UUDD: 32, 32L and 32R.

This can be verified from the Navigraph charts as well as the following source (as an example):

https://acukwik.com/Airport-Info/UUDD

**Comment by dga711** [comment] 2020-11-06 16:16
Yeah, still the game only gives us 32L 32R
![image](https://user-images.githubusercontent.com/2995606/98388994-c2f2d280-2053-11eb-9a15-583659b473da.png)

Not sure yet where this comes from.

**Comment by dga711** [comment] 2020-11-06 16:17
Cross checked in LittleNavMap with MSFS scenery (with navigraph)
![image](https://user-images.githubusercontent.com/2995606/98389179-00eff680-2054-11eb-9ecf-578297d4915b.png)

**Comment by cwburnett** [comment] 2020-11-06 16:27
14/32 is under construction at UUDD. I believe it will replace 14L/32R when complete (NOTAM says it will open in December, but that might be a placeholder). Or 14L/32R will be renamed 14C/32C. I don't know their plans. So nobody should be flight planning to an unfinished runway ;-)

That said, there's also a bug in MSFS right now, which doesn't attach the C to center runways, so at an airport with an actual 14L 14C 14R it labels them as 14L 14 and 14R further compounding the FMS problem.

It is on my list to track this down and then connect with Navigraph to see if we can't get it fixed, but I just haven't gotten to it yet....

![image](https://user-images.githubusercontent.com/70416619/98390234-4ee40a80-2012-11eb-8e69-56ee827aa575.png)

**Comment by havu1977** [comment] 2020-11-06 16:33
Ok, that makes sense. There was nothing in the Jeppesen airport briefing and the runway was in the SimBrief/Airac2012 database so I didn't even think that it is not in use yet :) Runway 32 is part of the SID charts as well (for example chart 30-3C).

So to summarize, you don't need me dropping anything at Navigraph at this stage I guess?

**Comment by cwburnett** [comment] 2020-11-06 16:39
Yea, I think the real issue is the coding of C runways, which I do need to talk with Navigraph about, but first need to clarify with Asobo so that it's all in sync. So, probably not worth raising it quite yet because I don't exactly know what I want them to do ;-)

**Comment by cwburnett** [comment] 2020-11-06 16:40
But the airway, we will try and track down, there are a few issues with airways and I'm not sure whether we're fixing them via a new flight plan manager or there are other aspects we need to address...so leave this one open for now.

**Comment by dga711** [comment] 2020-12-14 22:55
@cwburnett can you reevaluate if this issue is to be closed?

**Comment by cwburnett** [comment] 2020-12-15 16:52
In the latest update this is as fixed as it can be until we can collaborate more with Asobo on nav data coding

**Closed by cwburnett** 2020-12-15 16:52 UTC
Labels: Asobo'd, CJ4, bug
