### ISSUE TITLE
Working Title CJ4 capturing issue AP and ILS

### ISSUE THREAD

**Issue by MartinoQ** [Working-Title-MSFS-Mods/fspackages#576] opened 2020-11-26 09:17 UTC
First of all what a good work you delivered with the CJ4 working Title that said:
after the Patch 1.11.6.0 the CJ4 is not able to capture an ILS approach nor the glideslope and the localizer.
AP has also issues capturing the ALT, Just for your info, I imported the flight plan from Simbrief. Before the patch all was fine.
using version 0.7.2

**Comment by dga711** [comment] 2020-11-26 10:23
Thank you for your feedback. Though I will close it as a duplicate of #569

**Closed by dga711** 2020-11-26 10:23 UTC
