### ISSUE TITLE
[CJ4 v0.9.0] AP Selected VS rate not changing

### ISSUE THREAD

**Issue by JuiceBox7535** [Working-Title-MSFS-Mods/fspackages#781] opened 2021-01-08 07:37 UTC
Often when changing the autopilot mode to VS, the selected rate (ft per min) is locked and will not change using the pitch wheel on the mode control panel. It does, however, move the flight director. But the desired rate is locked. 

What's worse is it will not capture the selected altitude. Toggling VS mode off and back on sometimes resolves the issue. Didn't notice this on previous versions.

**Comment by haklis** [comment] 2021-01-11 13:59
I can confirm this behavior.  Has happened for me as well on 0.9.1.

**Comment by patbuser** [comment] 2021-01-16 18:21
I can also confirm, just happend for me on 0.9.1

**Comment by jacktorrance75** [comment] 2021-01-24 15:22
I can also confirm, just happend for me on 0.9.1

**Comment by okurz** [comment] 2021-01-26 08:31
I can confirm. A consistent workaround seems to be to always enable/disable/enable for the correctly selected values to show up and be effective

**Comment by dga711** [comment] 2021-01-27 09:20
This should be fixed in the coming update

**Closed by dga711** 2021-01-27 09:20 UTC
Labels: CJ4
