### ISSUE TITLE
CJ4 losses power

### ISSUE THREAD

**Issue by hosepuller** [Working-Title-MSFS-Mods/fspackages#1313] opened 2021-08-05 23:44 UTC
CJ4 loses power every time the wind changes direction.  There have been 40 knot changes in IAS when the wind changes direction from a nose or side wind to a tail wind.  This impacts the ability for  the aircraft to climb, especially at higher altitudes.  This was not happening in previous versions, so not sure what caused it. But it is chronic now.  Reading include high ITT and low N1 when struggling to gain altitude.  IAS of 180 or lower when this happens and tends to bleed off as you struggle to climb 

There is also an issue with the barometric pressure above FL180 that causes the ATC the give erroneous instructions  to climb or descend.  Frequently.  ATC is not picking up the fact that at FL180 standard barometric pressure applies.

**Comment by mattnischan** [comment] 2021-08-05 23:58
@hosepuller These are unfortunately sim issues and not issues with the CJ4. The engine performance is caused by high ISA temperatures that are erroneous in live weather, and the STD pressure issue is also known.

Both of these issues will be fixed in the next sim hotfix.

**Closed by mattnischan** 2021-08-05 23:58 UTC
