### ISSUE TITLE
CJ4 ILS needs to be manually tuned since SU7 in some cases

### ISSUE THREAD

**Issue by SheevAmidala** [Working-Title-MSFS-Mods/fspackages#1432] opened 2021-11-21 04:25 UTC
as per request on discord, i'm adding my approach details here (i have only flown one flight since the update so far)
Colombo, Sri Lanka (VCBI) to Dubai, Emirates (OMDB)

PUVA2D TRANS ULDOT into ILS30R/OMDB

the TOD was a couple NM before PUVAL and the CJ4 recieved the ILS beam on the first left turn right after PUVAL already but the arrival goes above the airport and heads away from it until, at roughly 30 NM distance, it turns back (2x 90° left turns) into final.

picture for reference how the flight path looks like

https://cdn.discordapp.com/attachments/767761280366805022/911665797959671909/Unbenannt.png

PUVAL is the first left hand turn in the north, according to the bearing pointer it's 28 NM away from the localizer "IDBR", at that point i was descending through FL320.
just short of the last two left hand turns on the flightpath i lost contact to the signal again ("LOC1 preset" switched back to "VOR1 preset"), at the same time there was the expected "CHECK LOCALIZER TUNING" message in the FMS. that message never went away, even though the "VOR1" switched into "LOC1" when i was back on final, indicating the CJ4 recieved the ILS signal again. i confirmed that by turning the bearing pointer on again, to see the localizer IDENT and distance shortly after the initial approach fix ULDOT, distance: 15 NM, 5600 ft, local baro...

once i recieved approach clearance from the tower, i pressed the approach button. that resulted in APPR1 LOC being the active mode and GS was armed but not active yet (above the glideslope). the PFD did not switch to the green needle, though, that was still purple until i switched the NAV source manually (2500 ft altitude and 7.6 NM away from the runway). it gave me the green needle (CRS 000) and i captured the glideslope in that very moment as well, GS turned green, but the CHECK LOCALIZER TUNING message stayed there until i was in my parking position and shut down the aircraft.

it's hard to tell if the flight path caused the bug but having read discord there seemed to be a couple more people reporting the same issue, that they had to manually tune the ILS for their approaches...
what i do not know is if i would have had to switch to the green needle manually if this was a straight in arrival considering everything was fine until i turned into final.
i'm gonna do another flight today (to another airport) and try to make sure it's an arrival, that doesn't cause me to lose the signal once i recieved it for the first time.

i can back trace every single detail because i recorded the entire flight.

EDIT: 2 small things i could add:

1: when you spawn your aircraft at an airport (parking position), right when you press FLY, there AUTOPILOT callout can be heard

2: the stand-by ADI brightness is slightly too bright for night flying. turning the brightness knob into the second lowest position at night causes the background lighting (keys and buttons) to be reduced by the appropriate amount but the stand-by ADI is almost as bright as if the turning knob was still in the 50% position. you can kind of counter that by turning the brightness of the PFD and MFD up a bit but IRL that would absolutely not be eye-frendly.

**Comment by mattnischan** [comment] 2021-11-21 15:06
Duplicate of #1428

**Closed by mattnischan** 2021-11-21 15:06 UTC
