### ISSUE TITLE
ILS Intercept Angle When APPR Engaged

### ISSUE THREAD

**Issue by OliveBeast20441** [Working-Title-MSFS-Mods/fspackages#228] opened 2020-10-11 01:24 UTC
I don’t know if this is an MSFS2020 issue or if it is specific to this aircraft, but the aircraft swings to a 40° intercept whenever the APPR mode is engaged, regardless of the heading selected prior to the intercept. In most cases, ATC provides a 30° intercept, however the aircraft will swing to a 40° intercept before finally capturing the localizer.

I have seen this behaviour on a couple other aircraft, but I do not know if it is a concern with all the different types of aircraft offered. If it is a sim issue, then please disregard.

**Comment by mattnischan** [comment] 2020-10-11 01:39
@OliveBeast20441 The subject and description on this don't seem to be complete.

**Comment by cwburnett** [comment] 2020-10-12 15:18
@OliveBeast20441 yes, right now, the autopilot is out of our hands, so controlling the intercept angle will have to wait until we have another solution, either an AP improvement from Asobo or we build our own. This is a known enhancement, but not a bug with the current codeset. Marking as closed. Thanks!

**Closed by cwburnett** 2020-10-12 15:18 UTC
Labels: CJ4
