### ISSUE TITLE
CJ4 v0.8.0 PFD VOR1 Problem

### ISSUE THREAD

**Issue by arklayton** [Working-Title-MSFS-Mods/fspackages#616] opened 2020-12-17 00:05 UTC
1. While just sitting on 35L at KCOS if I tune in the ILS freq (109.90) with the FMC the PFD responds as expected. But if I then immediately tune in a local VOR (112.5, BRK) with the FMC, the PFD does not change to show the VOR course info until I cycle the PFD through VOR2, FMS1 and then back to VOR1.

2. I also noticed when a VOR is tuned in clicking on the center of the CRS1 knob does not center the CDI., i.e., the course does not change to center the CDI. 

Thanks very much for the OUTSTANDING work on the CJ4!
Al

**Comment by dga711** [comment] 2020-12-19 22:46
#2 should be fixed in 0.8.1

**Comment by arklayton** [comment] 2020-12-20 04:38
Thanks for the info and the great and generous work of the WT team.

Al

**Comment by arklayton** [comment] 2020-12-20 21:04
Hi,

Unfortunately, it turns out the fix below is not correct. Perhaps there is a misunderstanding on what should happen.  A click on the center of the course knob when in VOR mode with a VOR tuned in should center the CDI – that is, adjust the course pointer to whatever it has to be so the CDI needle is centered and shows no offset. The tail of the course needle then indicates what VOR radial the a/c is on. This happens when the course pointer is adjusted to point directly at the VOR. Currently what I see in ver 0.8.1 is the course needle always changes to point ‘straight up’ in the direction that the a/c is heading and the CDI is still offset.

Thx,

Al

**Comment by dga711** [comment] 2020-12-20 21:11
@K20017

**Comment by K20017** [comment] 2020-12-20 21:19
What he is describing is the correct function for centering the CDI, just haven't gotten to it yet.

**Comment by arklayton** [comment] 2020-12-20 21:42
OK, thanks for the work on this!!

Al

**Comment by cwburnett** [comment] 2020-12-23 19:00
The NAV cycle bug in our code has been fixed. The change of the CRS knob behavior is already on the roadmap and is not a bug with current code. Closing. Thanks!

**Closed by cwburnett** 2020-12-23 19:00 UTC
Labels: CJ4
