### ISSUE TITLE
no ILS tuning / SU7 / CJ4 v0.12.9 / Navigraph / Aerosoft EDDK

### ISSUE THREAD

**Issue by CargoGuy** [Working-Title-MSFS-Mods/fspackages#1434] opened 2021-11-21 12:57 UTC
Hello,
ILS is not auto tuning / no blue ghost lines appear.
It says check loc tuning although a correct freq. is shown in FMS on multiple pages.
I have tried with reinstalling Aerosoft EDDK scenery but got same result. Even tried one flight with Navigraph navdata put on the last line in content.xml 
Please see some screenshots as illustration. We had similar bug in the past if I remember correctly.
Manual entering of ILS freq. does not change behavior.

![-2021-nov-20-012](https://user-images.githubusercontent.com/73137998/142762116-ac747b7c-75b8-4f43-9251-f6fd31997d5a.jpg)
![-2021-nov-21-007](https://user-images.githubusercontent.com/73137998/142762127-290d52df-eb0c-490c-8759-3301af7792dd.jpg)
![-2021-nov-21-003](https://user-images.githubusercontent.com/73137998/142762215-7c668ffc-1682-4426-bf50-c9402934d320.jpg)
![-2021-nov-20-008](https://user-images.githubusercontent.com/73137998/142762343-94136ac7-39d2-43e3-8815-dd3f8d5fb1eb.jpg)

Earlier yesterday I flew from LDDU to LDSP twice and had no problems with autotuning. Also addon (orbx LDSP)

**Comment by mattnischan** [comment] 2021-11-21 15:07
Duplicate of #1428

**Closed by mattnischan** 2021-11-21 15:07 UTC
