### ISSUE TITLE
[g3000-v0.2.0-pre1] Loading a procedure breaks the flightplan

### ISSUE THREAD

**Issue by Sakarias411** [Working-Title-MSFS-Mods/fspackages#263] opened 2020-10-15 01:43 UTC
g3000-v0.2.0-pre1

To reproduce : 
1. Input flightplan
2. Add approach procedure
3. Flight plan (visual route/magenta lines) disappears. (It might also break the flightplan internally because the plane won't follow any further waypoints after that, and one way to see the flightplan again is to create a DIRECT to any airport)

![image](https://user-images.githubusercontent.com/4887819/96064925-8559ba00-0e98-11eb-9578-0c3bd55666ec.png)

**Comment by cywang90** [comment] 2020-10-15 14:48
I'm having trouble reproducing this. Can you please provide more information, including:

- Does this happen for all flight plans/all approaches?
- If no to above, can you provide an example of a flight plan+approach that reproduces the problem? (if you could include all waypoints in the flight plan that would be appreciated)
- Does it matter when the approach is added? (i.e. on ground vs en route vs already flying a different approach, etc)

**Comment by Sakarias411** [comment] 2020-10-15 15:25
Hello @cywang90 
This is very strange, I wanted to take a video to show you the issue but now.. it's working as intended.

**Comment by cywang90** [comment] 2020-10-15 15:29
There are a lot of bugs with flight plans present in the base sim code; this may be one of them. I will leave the issue open for now in case you do find a way to repro.

**Comment by helge000** [comment] 2020-10-17 11:55
@Sakarias411 - Can you verify that you do not encounter the known issue? I see the same with vanilla. This has yet to be addressed by Asbro. Pls check:
1. Wait until you get your expected approach/arrival. You get cleared to a waypoint;
2. Sync heading and put A/P to heading mode;
3. Go fight plan page and add the waypoint from step 1 as new Enroute Waypoint
4. Go to Procedures, load the procedure you have clearance for -> **The Procedure should load successfully now**
5. Go back to flight plan, select the waypoint from step 1, and activate *direct to*
6. Switch A/P back to nav mode

The above workaround works for me since 1.8.x

**Comment by cywang90** [comment] 2021-04-25 22:27
Closed for outdated issue.

**Closed by cywang90** 2021-04-25 22:27 UTC
Labels: G1000, G3000
