### ISSUE TITLE
CJ4 v0.8.1 Route issue: KATL to KBWI with Navigraph data

### ISSUE THREAD

**Issue by Pickafivestring** [Working-Title-MSFS-Mods/fspackages#665] opened 2020-12-20 16:33 UTC
JACCC2 KELLN Q58 PEETT THHMP RAVNN6  

Issue 1:  Q58 not selectable as an airway off the JACCC2 departure.
Issue 2:  STARs do no populate in the FMS for KBWI, with or without a route entered.

Repeatable.

**Comment by dga711** [comment] 2020-12-20 16:41
1. We have a buge where we can't connect airways to the last departure fix. A workaround for now would be to add the fix manually again and then connect from there. Will be fixed.
2. Will check

**Comment by erictg** [comment] 2020-12-21 03:28
@Pickafivestring For issue 2, I think that the problem you are having is because of MSFS. KBWI is completely missing runway 15R/33L and still has the old runway. It probably doesn't know how to handle the navdata not matching the airport. I'd try to see if you can reproduce this error on an airport that is accurate is MSFS.

**Comment by dga711** [comment] 2021-01-02 18:49
Thanks for the information @erictg 

I don't see any more to do for us here right now. Feel free to reopen if there is something new.

**Closed by dga711** 2021-01-02 18:49 UTC
Labels: CJ4, bug

**Comment by erictg** [comment] 2021-01-02 21:13
@Pickafivestring there's a community fix for KBWI on [flight sim.to](https://flightsim.to/file/955/baltimore-washington-international-thurgood-marshall-airport)
