### ISSUE TITLE
Issue with PFD map display

### ISSUE THREAD

**Issue by rfputtini** [Working-Title-MSFS-Mods/fspackages#556] opened 2020-11-13 18:22 UTC
Hi guys! Yesterday while flying by night, the mini-map on both PFDs started acting weird. Every once in a while the airspaces would flash and get out of the map frame. No particular action triggered this, only small movements due by turbulence maybe.
This glitch sometimes did flash, sometimes it was more permanent, so I had time to take these screenshots.
Of course, this was with all Working Title/FS2020 latest versions, and the TBM930 improvement mod.
Latest nVidia drivers also with an GTX1080Ti.
Hope these screenshots helps.

![Screenshot (255)](https://user-images.githubusercontent.com/74426558/99106628-4c118880-25c3-11eb-87fb-9650eeda6907.png)
![Screenshot (252)](https://user-images.githubusercontent.com/74426558/99106639-50d63c80-25c3-11eb-95a1-70da7444032c.png)

**Comment by cywang90** [comment] 2020-11-14 18:45
Duplicate of #511

**Closed by cywang90** 2020-11-14 18:45 UTC
