### ISSUE TITLE
G1000: VOR course color should be green

### ISSUE THREAD

**Issue by bachian** [Working-Title-MSFS-Mods/fspackages#236] opened 2020-10-11 23:14 UTC
This is a small fix, but it jumps on eye for who a used to the real G1000 unit.

On PFD, VOR course color should be green. Only GPS course is magenta.

![Desktop Screenshot 2020 10 11 - 20 04 05 73](https://user-images.githubusercontent.com/29262832/95692741-5a543980-0bfe-11eb-9412-69f1acc33e09.png)

**Comment by rsparkyc** [comment] 2020-10-12 01:07
I think this is a duplicate of this: https://github.com/Working-Title-MSFS-Mods/fspackages/issues/64

**Comment by knighty** [comment] 2020-10-12 01:13
https://streamable.com/8e45lo 

Will be fixed in an upcoming release. Thanks for the note

**Comment by bachian** [comment] 2020-10-12 01:54
Sorry, I didn't see it was already reported.

I'm really impressed by what you are doing guys! Great job!

**Comment by rsparkyc** [comment] 2020-10-12 13:26
oh man, I was just working on a PR for this too...

Can I ask what branch I should be looking in for changes that have been done? I looked in main but didn't see any changes there that seemed relevant to this.

**Comment by knighty** [comment] 2020-10-12 15:02
The branch doesn't really exist in the current code base, it's a full rearchitecture of the Asobo code to make it more extensible and performant. Unfortunately this means it's not really in a state to do much work alongside until it's done but I've been working as rapidly as possible to try to get the baseline to vanilla so it can be used again, but having to redo all of their work is obviously a rather lengthy task. It's in a pretty buggy state and this push is a tad old at the time of me posting it but, https://github.com/knighty/fspackages/tree/develop/g1000-rearchitecture you can have a look here at the current dev version if you wish. Note you'll need SASS for building it which you can get the standalone from https://sass-lang.com/install and dump it in a build-tools folder in root. I apologise for this being a pain but the codebase really needed a full rearchitecture to facilitate further development

**Closed** 2021-11-20 18:59 UTC
Labels: G1000, nonprototypical
