### ISSUE TITLE
CJ4 - PERF INIT ZFW Calculation

### ISSUE THREAD

**Issue by Graeme1873** [Working-Title-MSFS-Mods/fspackages#1102] opened 2021-04-10 17:10 UTC
Hi there.

I’ve encountered a weird problem in 0.12.0.  When entering the PAX and Cargo details on the PERF INIT page the ZFW calculation doesn’t seem to calculate properly.  Prior to 0.12.0 I could match up the ZFW in the FMS with the MSFS loading screen by using the same PAX and cargo info but now it doesn’t align.  To see an example of what I mean if you try adding 1 PAX @ 77kg into the PERF INIT page of the FMS, the calculated ZFW only increases by 35kg.

I get round this by just entering the ZFW directly but does seem like it might be a hug?

cheers
Donald

**Comment by thor** [comment] 2021-04-25 17:58
I can confirm this in 0.12.1. I think the issue is that the weight calculation for the passengers is fixed in pounds rather than kilograms. Note that if you enter the weight as 6/170, assuming you have six passengers (incl. pilot and co-pilot), with a weight of 170 lbs per passenger (77 kg is approx. 170 lbs), then you'll get the correct values.

Switching the units to imperial will result in the *weight per passenger* also changing, but then being erroneously high. Using 6/170 while the default unit is imperial yields expected numbers.

**Closed** 2021-05-25 15:01 UTC
