### ISSUE TITLE
Perf Menu keeps reverting to Fuel Management page

### ISSUE THREAD

**Issue by Captherky** [Working-Title-MSFS-Mods/fspackages#414] opened 2020-10-25 18:20 UTC
The Perf page in the FMC wont stay up. It keeps reverting to the Fuel Management page. I have not enough time to enter any figures before it reverts.

**Comment by dga711** [comment] 2020-10-25 18:46
Duplicate of #256

**Closed by dga711** 2020-10-25 18:46 UTC
