### ISSUE TITLE
CJ4 0.9.0 - GPS track disappears or is inaccurate in certain PFD range settings

### ISSUE THREAD

**Issue by CORTRacer31** [Working-Title-MSFS-Mods/fspackages#787] opened 2021-01-08 17:28 UTC
I am currently conducting a flight from KDVT to KBTF and have noticed that, at the lower PFD zoom ranges (10, 25), the GPS track for my flight plan in the MFD disappears. I also noticed that, when I was entering the flight plan prior to engine start, that when I went through the PLAN review to make sure everything was input correctly, the GPS track did not connect to any of my waypoints. The plane seems to be navigating itself correctly, so I think it's just a display glitch.

**Comment by dga711** [comment] 2021-01-08 18:34
Duplicate of #641

**Comment by dga711** [comment] 2021-01-08 18:34
That tracks disappear will be hotfixed in a 0.9.1 release very shortly.

**Closed by dga711** 2021-01-08 18:34 UTC
