### ISSUE TITLE
CJ4 drifting off vertical path RNAV approach

### ISSUE THREAD

**Issue by N38TM** [Working-Title-MSFS-Mods/fspackages#926] opened 2021-02-14 18:24 UTC
Flying RNAV 28 approach to KCAG once on GP, plane slower drifted and bank left.
Happens at other locations as well but not every airport.

**Comment by midohioboarder1** [comment] 2021-02-14 20:18
I just flew from KBJC to KCAG via ECHOA transition.  Didn't find RW28.  Found RNAV RW25.  Not using Navigraph though if that makes a difference.   Everything went smooth except initial intercept of flight plan.  Running latest version.  Wanted to see if I had the same experience.

**Comment by N38TM** [comment] 2021-02-14 20:47
I probably misspoke on the RNAV rw. I'll try it again and see if it
repeats. Maybe I was close to stall speed.. if that would cause it.

**Comment by dga711** [comment] 2021-03-14 11:33
At that point in time I think there were some issues with the stall speeds. There also seems to be a problem with invisible icing in the sim, which can cause this.

Since I cannot really reproduce this, I will close the issue.

If the issues persists and you have new information, feel free to reopen. Thanks

**Closed by dga711** 2021-03-14 11:33 UTC
Labels: CJ4, flight model
