### ISSUE TITLE
G3000 green bar missing from wind options on PFD

### ISSUE THREAD

**Issue by ccapilot** [Working-Title-MSFS-Mods/fspackages#313] opened 2020-10-18 08:04 UTC
when you select PFD settings - other PFD settings - wind, all the options are working to change the wind display options, however the green line indicating which one is selected is missing. The green line works only for OFF selection, but is missing for WIND 1, 2 or 3 options.

**Comment by helge000** [comment] 2020-10-18 12:50
@ccapilot - FYI: The Working Title G3000 seems to model the real world one - it cannot display wind data on the ground (AFAIK). 
That said, you are hitting a bug bug from vanilla: Green bar not displayed when wind calm/0.

**Comment by ccapilot** [comment] 2020-10-18 13:16
@helge000 I think I was not quite clear... What I am referring to are the the green bar that shows which wind option is selected, it has nothing to do with if wind data can or can not be displayed...
as you can see in the pics attached only the OFF green bar is working, the other option are not..
![pfd1](https://user-images.githubusercontent.com/71601106/96368608-b3275300-1165-11eb-88bd-bd5da9c983c2.jpg)
![pfd2](https://user-images.githubusercontent.com/71601106/96368612-b4f11680-1165-11eb-92ce-a3858d28880b.jpg)

**Comment by helge000** [comment] 2020-10-18 13:32
@ccapilot - you where quite clear, maybe I was not? You can clearly see ``NO WIND DATA` in your screenshots. As soon as there is wind, the buttons show green. Give it a try when airborne.

![2020-10-18 15_31_24-Microsoft Flight Simulator - 1 9 5 0](https://user-images.githubusercontent.com/13696924/96368925-0c3bba80-1157-11eb-90a4-330c7ee0e48a.png)

**Comment by cywang90** [comment] 2020-10-18 15:08
You should still be able to select wind options even on the ground, so this is a bug. It will be addressed in an upcoming hotfix.

**Comment by ccapilot** [comment] 2020-10-18 15:10
@helge000 ok apologies, I did not understood that, ok. So basically those bars work only while airborne and as long as the wind is not zero... I am not sure is like that in real life.. but I have not way to test that... I a pretty sure that those bars should be visible always, even on the ground or with zero wind.

**Comment by cywang90** [comment] 2020-10-18 15:15
> @helge000 ok apologies, I did not understood that, ok. So basically those bars work only while airborne and as long as the wind is not zero... I am not sure is like that in real life.. but I have not way to test that... I a pretty sure that those bars should be visible always, even on the ground or with zero wind.
See my post above. The bars should still work while on the ground (but the display will always read NO WIND DATA).

**Comment by helge000** [comment] 2020-10-18 15:19
@ccapilot - I would also love a way to test it in real life :) - Please correct me if I'm wrong - the real TBM cannot measure wind data when on the ground. 
Also, @cywang90 's workaround in the PFD settings works well. I might add even if the bar does not light up the wind option is is still changed correctly.

A 🥇 for @cywang90 and the working title team for fixing all the stuff Asbro should fix ;)

**Comment by cywang90** [comment] 2020-10-18 15:22
> Please correct me if I'm wrong - the real TBM cannot measure wind data when on the ground.

That's correct. It will display NO WIND DATA while on the ground. However, you should still be able to select between the wind options while on the ground and it will remember it when you get in the air. Right now the mod is bugged and won't allow this but it will be fixed very soon.

**Comment by helge000** [comment] 2020-10-18 15:27
>Right now the mod is bugged and won't allow this but it will be fixed very soon.

Just to make this point clear: The vanilla G3000 does the same thing - it's not a bug of the mod IMHO.

**Closed** 2020-10-18 17:19 UTC
Labels: G3000, bug
