### ISSUE TITLE
Can't turn off FD

### ISSUE THREAD

**Issue by nrcrate** [Working-Title-MSFS-Mods/fspackages#643] opened 2020-12-19 00:33 UTC
Have noticed that I am unable to turn off the flight director when, for example, I am flying a visual approach or pattern. Will attempt to reproduce and make sure it is a consistent issue- this has only started since 0.8 and did not occur before.

**Comment by nrcrate** [comment] 2020-12-19 00:44
I should add- when AP is disconnected and you click the FD button, the FD does go away on the PFD. But it returns a second or so later in the state it was in prior.

**Comment by nikilase** [comment] 2020-12-19 01:00
Seems to be a duplicate of #624 and actually a bug by Asobo.

**Closed** 2020-12-19 10:19 UTC
Labels: Asobo'd, CJ4
