### ISSUE TITLE
G3000 0.4.0 RELEASE VERSION GPU & FPS DROP BY 50% OR MORE AFTER FLYING FOR 1 HOUR OR MORE

### ISSUE THREAD

**Issue by DiBarkis** [Working-Title-MSFS-Mods/fspackages#902] opened 2021-02-03 19:33 UTC
I think there might be an issue with the G3000 v0.40. About 1-2 hours in flight, the GPU usage drops drastically, and so does performance, resulting in about 50% FPS drop. If I switch to outside view, everything is OK. This is not about how demanding the scenery is because I thought so at first until after this flight, I restarted MSFS and started another flight on the same destination scenery, and FPS was more than double! I took off and came to the same spot (approach), at the same time of the day, same day of the year, same weather, same everything, and I had double the FPS, even after I landed. That's when I noticed that after flying for about one to two hours on EVERY flight regardless of scenery, only 50-60% of my GPU was being used, whereas if I started on the same scenery, it's used 99-100%. I've monitored it for many sceneries and the usage drop starts about 1 hour in the flight, and the longer the flight, the less the final FPS at destination. This doesn't happen with the v0.3.4. Does anyone else have this issue
![GPU_FPS_DROP 02](https://user-images.githubusercontent.com/47131139/106798988-b5d28900-662c-11eb-8a00-168fd2426513.jpg)

**Comment by cywang90** [comment] 2021-02-03 22:47
Duplicate of #900

**Closed by cywang90** 2021-02-03 22:47 UTC
