### ISSUE TITLE
G1000: Engine display not working in 0.3.1 pre1

### ISSUE THREAD

**Issue by TheFrett** [Working-Title-MSFS-Mods/fspackages#179] opened 2020-10-04 07:43 UTC
Hi,

On the latest pre-release (commit 59f8ca59d58146513c5e0f5355a6d2dc80175ef1), the engine display is not working anymore in conjunction with the G36 mod v0.5. See screenshot below. I checked the files but nothing about the WTEngineDisplay changed in your mod. That is about as far as my troubleshooting capabilities go.

This may be a duplicate of #174, but not sure due to lack of details in that issue. 

![Screenshot (273)](https://user-images.githubusercontent.com/11409383/95009897-a236f780-0625-11eb-9754-628fb64c0a9d.png)

**Comment by kaosfere** [comment] 2020-10-04 16:55
Yeah, I'm pretty sure that was the same issue.   -pre2 should take care of this:

https://github.com/Working-Title-MSFS-Mods/fspackages/releases/download/g1000-v0.3.1-pre2/workingtitle-g1000-v0.3.1-pre2.zip

Thanks for the report and sorry for the trouble.

**Comment by promethues5500** [comment] 2020-10-04 17:32
"This may be a duplicate of #174, but not sure due to lack of details in that issue."

Indeed it was, but thank you for posting. I'm new to using Github and still learning the ropes. The posted fix did indeed solve the issue, fyi. Engine gauges looking great and working perfectly.

**Comment by kaosfere** [comment] 2020-10-04 17:39
Awesome, happy to hear it.  :D   I'll go ahead and close this one then.

**Closed by kaosfere** 2020-10-04 17:39 UTC
Labels: G1000, bug
