### ISSUE TITLE
Black FMC in 0.8.1

### ISSUE THREAD

**Issue by TomAce77** [Working-Title-MSFS-Mods/fspackages#653] opened 2020-12-19 23:29 UTC
I get a black screen on FMC in 0.8.1. Create a flight plan in MSFS and press fly. Start battery, avionics dispatch, In FMC I align GPS (probably not necessary) and then go to IDX, page 2 and FPLN RECALL. It start loading, and after 2 sec it goes black.

Ex: LOWI > RUM > RTT > OBEDI > NIGSI > BALAD > NIGS1W ( Arrival) > ILS 11 (Approach) > LOWW

Have G1000 and G3000 installed in Community folder, for your information. 

Made a route from LOWW to LOWI earlier, where I made a route in MSFS (loaded in from SimBrief, used load function in MSFS menu), and did not use FPLN RECALL, but instead punched in route manually in FMC. That went fine.

Best regard, Thomas (TomAce)

**Comment by dga711** [comment] 2020-12-19 23:37
Possible duplicate of #619

**Comment by TomAce77** [comment] 2020-12-20 00:00
![Mods I use](https://user-images.githubusercontent.com/72699621/102702050-5841d300-425e-11eb-975d-897773556d4f.jpg)

These are the mods I use. Never had any problem with them before. Only "old" mods which I think is "approved"

**Comment by dga711** [comment] 2020-12-20 00:13
Ok. Thats a lot ;)

Well. As said, I would ask you for to try it without any of these mods (navigraph, garmins, a32nx can stay)
So we can rule any conflict out. Sometimes things conflict even if it doesn't make sense at first.

Thank you!

**Comment by dga711** [comment] 2020-12-20 00:16
And let me add. I just fixed a problem (for next patch) on our side which made it so you can't bring the FMS back by pressing a button for other pages. This should at least help when it happens in the future.

**Comment by dga711** [comment] 2021-01-03 13:07
Feel free to reopen when it still happens in the upcoming 0.8.5. Thanks

**Closed by dga711** 2021-01-03 13:07 UTC
Labels: CJ4, question
