### ISSUE TITLE
g3000-v0.4.2 in TBM930 freezes MSFS when near or at HUEN airport

### ISSUE THREAD

**Issue by Audytoriusz** [Working-Title-MSFS-Mods/fspackages#1019] opened 2021-03-15 08:44 UTC
I am writing here for the first time and not knowing if that is the right place and the right way.

Yesterday, while flying towards Entebbe Intl (HUEN) in TBM930, g3000 mod freezes the whole MSFS. Had to Task-Manager End-task. Later tried different planes and starting at the airport and I have narrowed the problem to: g3000 mod folder nearby HUEN.

Am I able to add labels (freeze, g3000, bug) here?

**Comment by TomazDrnovsek** [comment] 2021-03-18 18:34
I have the exact same freeze issue near HAAB airport, exactly at MEKEL waypoint.

**Comment by TomazDrnovsek** [comment] 2021-03-19 13:22
Actually, I'm getting these freezes all over southern Africa.

**Comment by cywang90** [comment] 2021-03-28 17:23
Couldn't reproduce this. Flew right over MEKEL and around HAAB. No freeze for me.

**Comment by TomazDrnovsek** [comment] 2021-03-28 17:35
> Couldn't reproduce this. Flew right over MEKEL and around HAAB. No freeze for me.

Really? I repeated it many times just to be sure. With the mod I get the freeze every time, without it I don't. What else could it be then?
Here’s a short video of the issue: https://photos.app.goo.gl/4PZvxPas9csz2Yee7

**Comment by cywang90** [comment] 2021-04-19 20:35
I've done some more testing and have so far isolated the issue to airway rendering in the nav map. So for now as a workaround you can turn off airways in map settings.

**Comment by TomazDrnovsek** [comment] 2021-04-21 07:56
Thnak you for the information! I will do that.

**Comment by cywang90** [comment] 2021-04-25 22:25
Fixed with v0.6.0

**Closed by cywang90** 2021-04-25 22:25 UTC
Labels: G3000, QA In Progress, bug, freeze
