### ISSUE TITLE
G5000 - Missing arrival / approach

### ISSUE THREAD

**Issue by bogdanrau** [Working-Title-MSFS-Mods/fspackages#740] opened 2020-12-31 17:05 UTC
When using the G5000 in a Longitude, FPL from KMEM to BIKF, it's missing all approaches and arrivals for BIKF. I'm using Navigraph for this data and it's available in both Navigraph and Simbrief.

**Comment by e-racer** [comment] 2020-12-31 23:38
Happy new year!

I had the same issue in ST. Tropez and wrote a ticket at Navigraph... they told me to uninstall all navigraph data and also the installer (although it was the current beta 19 version). I downloaded again the same installer and installed everything new, and it solved the problem! 

Have a try..

Best Regards

**Comment by bogdanrau** [comment] 2021-01-02 17:52
Happy New Year! I uninstalled and reinstalled (both data and the beta installer) and have the newest AIRAC. No go. And, perhaps related, it looks like some VOR/VORTACs are not visible when searching for them as well. For example, entering OLM or PDT gives no result, and just enters a placeholder / empty waypoint. Not sure if this is related to the original issue or not, but figured I'd mention it.

**Comment by Cugix** [comment] 2021-01-02 19:04
What I noticed is it won't show the approach waypoints on the Garmin while they do show up in the VFR Map (V).

**Comment by cywang90** [comment] 2021-01-04 20:57
Duplicate of #705

**Closed by cywang90** 2021-01-04 20:57 UTC
