### ISSUE TITLE
CTD when selecting ATC or any menu item from Styled_g3000_TSC

### ISSUE THREAD

**Issue by Captherky** [Working-Title-MSFS-Mods/fspackages#350] opened 2020-10-21 15:31 UTC
I get CTD when using the workingtitle-g3000 (latest 2.1). When trying to select any menu items from ATC menu or the Styled_g3000TSC.

I dont have any TBM mods installed.

I have workingtitlegx, UWA light mod TBM930, and Styled g3000TSC. Only other mods are the G36 Bonanza mod and liveries.

I dont have the workingtitle g1000 mod in the community folder because i read it may conflict.

I have the MS App Store Premium de lux install.

**Comment by cywang90** [comment] 2020-10-21 15:36
The WT g3000 mod isn't compatible with the touchscreen restyled mod. We are working to get the restyled mod integrated, but for now you have to choose one or the other.

**Comment by Captherky** [comment] 2020-10-21 15:40
> The WT g3000 mod isn't compatible with the touchscreen restyled mod. We are working to get the restyled mod integrated, but for now you have to choose one or the other.

Thanks for the heads up. You just saved me an hours testing mod add ons!

Appreciate it. Ill remove the touch screen mod and try again!

**Comment by Captherky** [comment] 2020-10-21 18:36
> The WT g3000 mod isn't compatible with the touchscreen restyled mod. We are working to get the restyled mod integrated, but for now you have to choose one or the other.


EDIT.

I just had another CTD!
I removed the Touchscreen mod, buy still had CTD when accessing the MFD menues?
Sorry. Looks like Im out of luck with your mod?

**Comment by Captherky** [comment] 2020-10-21 18:39
I removed the TSC mod and had another CTD when trying to access the MFD selection screen?

I only have the UWA TBM light mod, the workingtitle g100 and the workingtitle-gx mod installed.

Looks like im out of luck with your mod on the TBM?

Regards
David

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cywang90** [comment] 2020-10-21 18:46
Can you provide more details on the CTD please?

**Comment by Captherky** [comment] 2020-10-21 20:00
Yes.

Flight planned in Simbrief and exported MSFS.
No TSC mod on.
EGNH to EGCC
Take off climb AP on.
Everything looks ok.
I expand range of MFD and alter some brightness parameters.
Descent into EGCC I go to flight plan page and enter ATC assigned approach.
Go ack to MFD page.
Reduce range.
CTD

Previous three CTD were;

  1.  EGLL to EHAM take off climb on route nicely
  2.  Open ATC menu and click on menu item
  3.  CTD
EGLL to EHAM

  1.  Same as above.
  2.  At top of climb access MFD and click on map parameter.
  3.  CTD
EGLL to EHAM  same as above, except I removed the Touchscreen mod and the g1000 mod, just leaving UWAs TBM light mod, livery mod and the workingtitle GX mod. this time Click on MFD route page and scroll down route and CTD.

Seems to be every time I access the MFD menu it CTD, but only after about 15 minutes flying. Never before and I usually start with cold and dark.

It’s a CTD with no warning.
Thanks




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Captherky** [comment] 2020-10-22 10:11
Does it make any difference that I'm on Windows 1909 build? Do I need to be on 2004 build? Or doesnt it matter?

**Comment by Captherky** [comment] 2020-10-22 10:50
This seems to be the error, if its any use to you?

Log Name:      Application
Source:        Application Error
Date:          10/21/2020 7:34:07 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WINDOWS-7M2S8CI
Description:
Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x5f7c8cf2
Faulting module name: CoherentUIGT.dll, version: 0.0.0.0, time stamp: 0x5f7613c5
Exception code: 0xc0000005
Fault offset: 0x000000000013f4e7
Faulting process id: 0x2f90
Faulting application start time: 0x01d6a7d4824ae9b2
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe\CoherentUIGT.dll
Report Id: 1cebe7b8-7d6c-40bc-8035-518f15d107b9
Faulting package full name: Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-21T18:34:07.713267400Z" />
    <EventRecordID>16396</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WINDOWS-7M2S8CI</Computer>
    <Security />
  </System>
  <EventData>
    <Data>FlightSimulator.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f7c8cf2</Data>
    <Data>CoherentUIGT.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>5f7613c5</Data>
    <Data>c0000005</Data>
    <Data>000000000013f4e7</Data>
    <Data>2f90</Data>
   <Data>01d6a7d4824ae9b2</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe\CoherentUIGT.dll</Data>
    <Data>1cebe7b8-7d6c-40bc-8035-518f15d107b9</Data>
    <Data>Microsoft.FlightSimulator_1.9.5.0_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cywang90** [comment] 2020-10-22 14:03
> Does it make any difference that I'm on Windows 1909 build? Do I need to be on 2004 build? Or doesnt it matter?

It shouldn't matter with respect to the mod. As for the CTDs, I'm unable to reproduce them. From your descriptions, the first one sounds like it may be related to a known vanilla bug where messing around with the flight plan in-flight may cause CTDs. The other ones I'm not sure. The mod should not affect anything to do with ATC... but you never know. Can you confirm that these crashes don't happen with no mods installed?

**Comment by Captherky** [comment] 2020-10-22 14:06
Yes I removed the mod and did two complete flights with no problems at all.  I will re test with all mods removed except this one and report back.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Captherky** [comment] 2020-10-22 14:58
OK with no mods in the community folder first flight and got no CTD.

However, I entered a Dirto waypoint, shortly after take off, using right FMC screen in flight plan mode. . This locked up the screen and wouldn’t allow me to access the PFD or NAV COM screen from the push buttons. I couldn’t scroll the flight plan and couldn’t enter an enroute way point. The type enter had gone.

I placed the left FMC into MFD mode to try to see the flight plan and it too had frozen at the same position as the right FMC.

I was unable to see the flight plan or add an enroute waypoint. The text entry had frozen also. So both the FMC screens were locked up.

Hope that helps.

I hope you can reproduce the FMC flight plan entry lock ups?  That may be a partial cause of my previous CTDs. Since I tend to use the flight plan pages often.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cywang90** [comment] 2020-10-22 15:10
> using right FMC screen in flight plan mode.

What airplane are you flying? The TBM does not have an FMC.

**Comment by Captherky** [comment] 2020-10-22 15:38
Sorry, that’s the right hand screen that allows you to see PFD,MFD and comms and the flight plan. Don’t know what else to call it. Yes of course Im in the TBM!
Sorry

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cywang90** [comment] 2020-10-22 15:52
> Sorry, that’s the right hand screen that allows you to see PFD,MFD and comms and the flight plan. Don’t know what else to call it. Yes of course Im in the TBM!

Ah OK, I think you're referring to the touchscreens. Unfortunately, crashes/freezes after messing with the flight plan too much is a vanilla issue. We may be able to fix the issue in the future but so far we haven't put much work into identifying the cause. For now the workaround is to use the flight plan page as sparingly as possible. Set up your flight plan in the world map, etc.

**Comment by Captherky** [comment] 2020-10-22 16:40
OK thanks.

So the CTD I was getting must have been one of the mods?
Apart from the TSC mode which you identify as troublesome, I only use repaints, airports and the workingtitle mods for g1000. Oh and the G36 improvement mod.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cywang90** [comment] 2020-12-23 15:27
This seems to be an obsolete issue, so I'm closing this for now.

**Closed by cywang90** 2020-12-23 15:27 UTC
Labels: G3000
