### ISSUE TITLE
Honeycomb Bravo Throttle - Increment problem caused by gear lever

### ISSUE THREAD

**Issue by TomAce77** [Working-Title-MSFS-Mods/fspackages#1072] opened 2021-03-30 17:03 UTC
Hi
I have the Honeycomb Bravo Throttle which has been used with all default planes, FBW A320neo and the new CRJ from Aerosoft. But I have also used it with the CJ4. Now I have problem with the heading bug and the altitude knob which changes with 10's (heading bug) and 1000's (altitude). I have been informed that it is a problem in the sim (https://forums.flightsimulator.com/t/heading-increment-bug-10-degree-instead-of-1-explained/290173), but as far as my experience this only happens to this plane and this wasn't a problem before Sim Update 3.

I have tried to remove bindings and found that it is the gear lever binding on the Honeycomb that causes it. But as I said it only appears on this plane, and not the other ones. Can you please look into this?

**Comment by mattnischan** [comment] 2021-03-30 17:14
@TomAce77 Unfortunately, we have no access to the clickspot behavior or knob acceleration at all from aircraft code. All of that is inside the sim, so it would not be something we could address on the plane side.

I believe the issue is slated to be addressed in either World Update 4 or Sim Update 4 on the sim side.

**Closed by mattnischan** 2021-03-30 17:14 UTC
