### ISSUE TITLE
freezes in the flight plan if you click the down arrow. G3000

### ISSUE THREAD

**Issue by marway84** [Working-Title-MSFS-Mods/fspackages#493] opened 2020-11-01 15:41 UTC
2) Select MFD
3) Select Flight Plan
4) Add a source and destination
5) Select the destination so that the waypoint sub-menu displays
6) Click the down arrow.

This works mod works fine on v0.2.2 https://flightsim.to/file/2195/fix-tbm-930-mfd-freeze-when-scrolling-down-in-the-flight-plan

but 0.3.0-pre CTD

**Comment by cywang90** [comment] 2020-11-01 16:56
This is a duplicate of #382.

**Closed by cywang90** 2020-11-01 16:56 UTC
